//! Proc macros for compile-time struct field merging.
//!
//! Two macros work together:
//!
//! - `#[derive(Fields)]` on each source struct generates a companion
//!   callback macro that can replay its field definitions.
//! - `#[combine_fields(A, B, C)]` on the target struct merges in the
//!   fields from structs `A`, `B`, `C` (which must derive `Fields`).
//!
//! # Example
//!
//! ```ignore
//! use combine_structs::Fields;
//!
//! #[derive(Fields)]
//! pub struct Foo {
//!     pub x: i32,
//! }
//!
//! #[derive(Fields)]
//! pub struct Bar {
//!     pub y: String,
//! }
//!
//! #[combine_fields(Foo, Bar)]
//! #[derive(Debug, Default)]
//! pub struct Combined {
//!     pub z: bool,
//! }
//!
//! // Produces a struct with fields x, y, and z.
//! ```

use proc_macro::TokenStream;
use proc_macro2::{Delimiter, Group, Ident, Punct, Spacing, Span, TokenStream as TokenStream2};
use quote::{format_ident, quote};
use syn::{Data, DeriveInput, Fields, ItemStruct, parse_macro_input};

/// Derive macro that generates a companion callback macro for struct field
/// merging.
///
/// The generated macro is named `__combine_fields_{StructName}` and follows
/// the callback pattern: it appends the struct's field definitions (with all
/// attributes, doc comments, and visibility preserved) to the callback's
/// arguments.
///
/// # Panics
///
/// Panics if applied to an enum or union (only named structs are supported).
#[proc_macro_derive(Fields)]
pub fn derive_fields(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let struct_name = &input.ident;
    let macro_name = format_ident!("__combine_fields_{}", struct_name);

    let fields = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(named) => &named.named,
            _ => panic!("Fields derive only supports structs with named fields"),
        },
        _ => panic!("Fields derive only supports structs"),
    };

    // Collect each field's tokens: attributes + vis + name + type
    let field_tokens: Vec<TokenStream2> = fields
        .iter()
        .map(|f| {
            let attrs = &f.attrs;
            let vis = &f.vis;
            let name = f.ident.as_ref().expect("named field must have ident");
            let ty = &f.ty;
            quote! {
                #(#attrs)*
                #vis #name: #ty,
            }
        })
        .collect();

    // Build the macro_rules! body manually to emit `$` tokens without
    // relying on the unstable `$$` meta-variable expressions feature.
    let macro_body = build_callback_macro_body(&field_tokens);

    let expanded = quote! {
        /// Generated by `#[derive(Fields)]` — callback macro for struct
        /// field merging.
        #[doc(hidden)]
        macro_rules! #macro_name {
            #macro_body
        }
    };

    expanded.into()
}

/// Attribute macro that merges fields from other `#[derive(Fields)]` structs
/// into the annotated struct.
///
/// # Example
///
/// ```ignore
/// #[combine_fields(CoreVocabulary, ApplicatorVocabulary)]
/// #[derive(Debug, Clone, Default)]
/// pub struct Schema {
///     // extra fields defined here
///     pub markdown_description: Option<String>,
/// }
/// ```
///
/// The macro generates a nested chain of `__combine_fields_*!` callback
/// macros that accumulate all fields, then emits the final struct definition.
///
/// # Panics
///
/// Panics if the attribute arguments are not a comma-separated list of
/// identifiers, or if the annotated item is not a struct with named fields.
#[proc_macro_attribute]
pub fn combine_fields(attr: TokenStream, item: TokenStream) -> TokenStream {
    let source_names = parse_macro_input!(attr with syn::punctuated::Punctuated::<Ident, syn::Token![,]>::parse_terminated);
    let input = parse_macro_input!(item as ItemStruct);

    let struct_attrs = &input.attrs;
    let struct_vis = &input.vis;
    let struct_name = &input.ident;
    let struct_generics = &input.generics;

    let extra_fields: Vec<TokenStream2> = match &input.fields {
        syn::Fields::Named(named) => named
            .named
            .iter()
            .map(|f| {
                let attrs = &f.attrs;
                let vis = &f.vis;
                let name = f.ident.as_ref().expect("named field");
                let ty = &f.ty;
                quote! { #(#attrs)* #vis #name: #ty, }
            })
            .collect(),
        _ => panic!("combine_fields only supports structs with named fields"),
    };

    // Build the terminal macro that will receive all accumulated fields
    // and emit the final struct definition.
    let terminal_name = format_ident!("__build_{}", struct_name);
    let terminal_body =
        build_terminal_macro_body(struct_attrs, struct_vis, struct_name, struct_generics);

    // Build the nested callback chain:
    //   __combine_fields_A!(__combine_fields_B!( ... __build_Schema!(extra_fields) ... ))
    let macro_names: Vec<Ident> = source_names
        .iter()
        .map(|name| format_ident!("__combine_fields_{}", name))
        .collect();

    // Innermost call: __build_Schema!(extra_fields...)
    let mut chain: TokenStream2 = {
        let mut inner = TokenStream2::new();
        for ft in &extra_fields {
            inner.extend(ft.clone());
        }
        quote! { #terminal_name!(#inner) }
    };

    // Wrap from inside out: __combine_fields_Last!( ... __combine_fields_First!( chain ) )
    for macro_name in macro_names.iter().rev() {
        chain = quote! { #macro_name!(#chain) };
    }

    let expanded = quote! {
        macro_rules! #terminal_name {
            #terminal_body
        }

        #chain;
    };

    expanded.into()
}

/// Build the `macro_rules!` body for a callback macro generated by
/// `#[derive(Fields)]`.
///
/// Produces a rule that captures a callback invocation and appends the
/// struct's fields to the callback's arguments:
///
/// ```ignore
/// ($callback:ident ! ( $($args:tt)* ) $($rest:tt)*) => {
///     $callback!($($args)* $($rest)* <field_tokens>);
/// };
/// ```
fn build_callback_macro_body(field_tokens: &[TokenStream2]) -> TokenStream2 {
    let callback = dollar_ident("callback");
    let args = dollar_ident("args");
    let rest = dollar_ident("rest");

    // Pattern: ($callback:ident ! ( $($args:tt)* ) $($rest:tt)*)
    let mut pattern_inner = TokenStream2::new();
    pattern_inner.extend(callback.clone());
    pattern_inner.extend(quote!(:ident !));

    let mut args_rep_inner = TokenStream2::new();
    args_rep_inner.extend(args.clone());
    args_rep_inner.extend(quote!(:tt));
    let args_group = Group::new(Delimiter::Parenthesis, dollar_rep(args_rep_inner));
    pattern_inner.extend([proc_macro2::TokenTree::Group(args_group)]);

    let mut rest_rep_inner = TokenStream2::new();
    rest_rep_inner.extend(rest.clone());
    rest_rep_inner.extend(quote!(:tt));
    pattern_inner.extend(dollar_rep(rest_rep_inner));

    let pattern = Group::new(Delimiter::Parenthesis, pattern_inner);

    // Body: $callback!( $($args)* $($rest)* <field_tokens> );
    let mut body_inner = TokenStream2::new();
    body_inner.extend(callback);
    body_inner.extend(quote!(!));

    let mut call_args = TokenStream2::new();
    call_args.extend(dollar_rep(args));
    call_args.extend(dollar_rep(rest));
    for ft in field_tokens {
        call_args.extend(ft.clone());
    }
    let call_group = Group::new(Delimiter::Parenthesis, call_args);
    body_inner.extend([proc_macro2::TokenTree::Group(call_group)]);
    body_inner.extend(quote!(;));

    let body = Group::new(Delimiter::Brace, body_inner);

    let mut result = TokenStream2::new();
    result.extend([proc_macro2::TokenTree::Group(pattern)]);
    result.extend(quote!(=>));
    result.extend([proc_macro2::TokenTree::Group(body)]);
    result
}

/// Build the `macro_rules!` body for the terminal macro generated by
/// `#[combine_fields]`.
///
/// Produces a rule that receives all accumulated fields and emits the
/// final struct definition:
///
/// ```ignore
/// ($(#[$meta:meta])* $vis:vis $field:ident: $ty:ty,)*) => {
///     #[derive(...)]
///     pub struct Schema {
///         $($(#[$meta])* $vis $field: $ty,)*
///     }
/// };
/// ```
fn build_terminal_macro_body(
    struct_attrs: &[syn::Attribute],
    struct_vis: &syn::Visibility,
    struct_name: &Ident,
    struct_generics: &syn::Generics,
) -> TokenStream2 {
    let meta = dollar_ident("meta");
    let vis = dollar_ident("vis");
    let field = dollar_ident("field");
    let ty = dollar_ident("ty");

    // Pattern: ( $($(#[$meta:meta])* $vis:vis $field:ident : $ty:ty ,)* )
    let mut unit_inner = TokenStream2::new();
    // #[$meta:meta]
    let mut attr_inner = TokenStream2::new();
    attr_inner.extend(quote!(#));
    let mut meta_bracket = TokenStream2::new();
    meta_bracket.extend(meta.clone());
    meta_bracket.extend(quote!(:meta));
    attr_inner.extend([proc_macro2::TokenTree::Group(Group::new(
        Delimiter::Bracket,
        meta_bracket,
    ))]);
    unit_inner.extend(dollar_rep(attr_inner));
    // $vis:vis
    unit_inner.extend(vis.clone());
    unit_inner.extend(quote!(:vis));
    // $field:ident
    unit_inner.extend(field.clone());
    unit_inner.extend(quote!(:ident :));
    // $ty:ty ,
    unit_inner.extend(ty.clone());
    unit_inner.extend(quote!(:ty ,));

    let pattern = Group::new(Delimiter::Parenthesis, dollar_rep(unit_inner));

    // Body: emit the struct with all accumulated fields
    // Build the field expansion: $($(#[$meta])* $vis $field: $ty,)*
    let mut field_expansion_inner = TokenStream2::new();
    field_expansion_inner.extend(dollar_rep({
        let mut attr_exp = TokenStream2::new();
        attr_exp.extend(quote!(#));
        let mut meta_bracket = TokenStream2::new();
        meta_bracket.extend(meta);
        attr_exp.extend([proc_macro2::TokenTree::Group(Group::new(
            Delimiter::Bracket,
            meta_bracket,
        ))]);
        attr_exp
    }));
    field_expansion_inner.extend(vis);
    field_expansion_inner.extend(field);
    field_expansion_inner.extend(quote!(:));
    field_expansion_inner.extend(ty);
    field_expansion_inner.extend(quote!(,));
    let field_expansion = dollar_rep(field_expansion_inner);

    let (impl_generics, ty_generics, where_clause) = struct_generics.split_for_impl();
    let _ = (impl_generics, ty_generics, where_clause);

    let mut body_inner = TokenStream2::new();
    body_inner.extend(quote! {
        #(#struct_attrs)*
        #struct_vis struct #struct_name #struct_generics
    });

    let mut struct_body = TokenStream2::new();
    struct_body.extend(field_expansion);
    body_inner.extend([proc_macro2::TokenTree::Group(Group::new(
        Delimiter::Brace,
        struct_body,
    ))]);

    let body = Group::new(Delimiter::Brace, body_inner);

    let mut result = TokenStream2::new();
    result.extend([proc_macro2::TokenTree::Group(pattern)]);
    result.extend(quote!(=>));
    result.extend([proc_macro2::TokenTree::Group(body)]);
    result
}

/// Produce `$ident` — a dollar sign followed by an identifier.
fn dollar_ident(name: &str) -> TokenStream2 {
    let mut ts = TokenStream2::new();
    ts.extend([proc_macro2::TokenTree::Punct(Punct::new(
        '$',
        Spacing::Alone,
    ))]);
    ts.extend([proc_macro2::TokenTree::Ident(Ident::new(
        name,
        Span::call_site(),
    ))]);
    ts
}

/// Produce `$( <inner> )*` — a macro repetition.
fn dollar_rep(inner: TokenStream2) -> TokenStream2 {
    let mut ts = TokenStream2::new();
    ts.extend([proc_macro2::TokenTree::Punct(Punct::new(
        '$',
        Spacing::Alone,
    ))]);
    ts.extend([proc_macro2::TokenTree::Group(Group::new(
        Delimiter::Parenthesis,
        inner,
    ))]);
    ts.extend([proc_macro2::TokenTree::Punct(Punct::new(
        '*',
        Spacing::Alone,
    ))]);
    ts
}
